### ISSUE TITLE
Merge with Kickball/awesome-selfhosted?

### ISSUE THREAD

**Issue by nodiscc** [juandecarrion/awesome-self-hosted#1]
Hi @juandecarrion a community effort to build a self-hostable applications list is currently taking place at https://github.com/Kickball/awesome-selfhosted. We have a fair amount of contributions already in; would you like to merge your list with ours?

Just check https://github.com/Kickball/awesome-selfhosted#contributing, fork the repository and send us your applications as Pull Requests. If you need help, please let us know!

**Comment by juandecarrion** [comment]
Hi @nodiscc, you are right, it will be better if we merge both. Can you do it?

**Comment by nodiscc** [comment]
Thanks for the quick reply! Added to our to-do list at https://github.com/Kickball/awesome-selfhosted/issues/141.

You're welcome to contribute more applications/do some cleanup/send feedback anytime. Just fork our repository, edit README.md, commit to a new branch and send a Pull Request.

**Comment by nodiscc** [comment]
@juandecarrion Done https://github.com/Kickball/awesome-selfhosted/pull/171

**Comment by juandecarrion** [comment]
Thanks!
